name: Debug Deploy

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  deployments: write

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'npm'
      
      - name: List directory contents
        run: ls -la
      
      - name: List index.html content
        run: cat index.html || echo "index.html not found"
      
      - name: List vite.config.ts content
        run: cat vite.config.ts || echo "vite.config.ts not found"
      
      - name: Show Node and NPM versions
        run: |
          node --version
          npm --version
      
      - name: Install dependencies
        run: npm ci
        
      - name: Update index.html paths
        run: |
          sed -i 's|src="/|src="./|g' index.html
          sed -i 's|href="/|href="./|g' index.html || echo "sed command failed"
          cat index.html
      
      - name: Ensure base is relative in vite.config.ts
        run: |
          sed -i 's|base:.*,|base: "./",|' vite.config.ts || echo "sed command failed"
          cat vite.config.ts | grep "base:"
      
      - name: Check package.json content
        run: cat package.json
        
      - name: Build with full debugging
        run: npm run build --verbose
        
      - name: List dist contents if build succeeded
        if: ${{ success() }}
        run: ls -la dist

  # No deploy step in debug workflow 