name: Simple Fix and Deploy

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  deployments: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Fix asset paths in index.html
        run: |
          cat > index.html << 'EOL'
          <!DOCTYPE html>
          <html lang="en">
            <head>
              <meta charset="UTF-8" />
              <link rel="icon" type="image/svg+xml" href="./favicon.svg" />
              <meta name="viewport" content="width=device-width, initial-scale=1.0" />
              <title>Sunset Septics</title>
              <meta name="description" content="Professional septic services in your area" />
              <!-- SPA routing support for GitHub Pages -->
              <script type="text/javascript" src="./index-redirect.js"></script>
            </head>
            <body>
              <div id="root"></div>
              <script type="module" src="./src/main.tsx"></script>
            </body>
          </html>
          EOL
          cat index.html

      - name: Fix vite.config.ts
        run: |
          sed -i 's|base:.*,|base: "./",|' vite.config.ts || echo "sed command failed"
          grep -n "base:" vite.config.ts

      - name: Create 404.html for SPA routing
        run: |
          mkdir -p public
          cat > public/404.html << 'EOL'
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <title>Sunset Septics</title>
            <script>
              // Handle SPA routing by redirecting to index
              var pathSegmentsToKeep = 0;
              var l = window.location;
              l.replace(
                l.protocol + '//' + l.hostname + (l.port ? ':' + l.port : '') +
                l.pathname.split('/').slice(0, 1 + pathSegmentsToKeep).join('/') + '/?/' +
                l.pathname.slice(1).split('/').slice(pathSegmentsToKeep).join('/').replace(/&/g, '~and~') +
                (l.search ? '&' + l.search.slice(1).replace(/&/g, '~and~') : '') +
                l.hash
              );
            </script>
            <meta http-equiv="refresh" content="0;url=./">
          </head>
          <body>
            <p>Redirecting to <a href="./">homepage</a>...</p>
          </body>
          </html>
          EOL
          cat public/404.html

      - name: Create index-redirect.js
        run: |
          cat > public/index-redirect.js << 'EOL'
          // Single Page Apps for GitHub Pages
          // MIT License
          // https://github.com/rafgraph/spa-github-pages
          // This script checks to see if a redirect is present in the query string,
          // converts it back into the correct url and adds it to the
          // browser's history using window.history.replaceState(...),
          // which won't cause the browser to attempt to load the new url.
          // When the single page app is loaded further down in this file,
          // the correct url will be waiting in the browser's history for
          // the single page app to route accordingly.
          (function(l) {
            if (l.search[1] === '/' ) {
              var decoded = l.search.slice(1).split('&').map(function(s) { 
                return s.replace(/~and~/g, '&')
              }).join('?');
              window.history.replaceState(null, null,
                  l.pathname.slice(0, -1) + decoded + l.hash
              );
            }
          }(window.location));
          EOL
          cat public/index-redirect.js

      - name: Build project
        run: npm run build

      - name: Copy CNAME file to dist
        run: |
          echo "sunsetseptics.ca" > dist/CNAME
          cat dist/CNAME

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 